require("lsp-zero")
require("lspconfig").clangd.setup({})
require("lspconfig").lua_ls.setup({})
require("lspconfig").cssls.setup({})
require("lspconfig").html.setup({})
require("lspconfig").tsserver.setup({})
